services:
  origin-store-database:
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: origin
      POSTGRES_PASSWORD: origin
      POSTGRES_DB: origin
    ports:
      - "25342:5432"
    profiles:
      - origin-store
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s
  file-storage:
    image: minio/minio:latest
    ports:
      - "45866:9000"   # Основной API для MinIO (S3-совместимый)
      - "45867:9090"   # Консоль управления MinIO
    environment:
      - MINIO_ROOT_USER=file-storage
      - MINIO_ROOT_PASSWORD=file-storage
    command: server /data --console-address ":9090"
    profiles:
      - origin-store
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://localhost:9000/minio/health/ready" ]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s
