spring:
  application.name: authorization
  docker.compose:
    profiles.active: authorization
  aop:
    proxy-target-class: false

  session:
    jdbc:
      table-name: http_session
      cleanup-cron: 0 */5 * * * *
  security:
    user:
      name: razornd
      password: changeme
    oauth2:
      authorizationserver:
        client:
          cli-app:
            require-proof-key: true
            registration:
              client-id: phototransit-cli
              client-name: PhotoTransit CLI
              client-authentication-methods: [ none ]
              authorization-grant-types: [ urn:ietf:params:oauth:grant-type:device_code ]



gg.jte:
  use-precompiled-templates: true
  template-suffix: .kte
