spring:
  application.name: authorization
  docker.compose:
    profiles.active: authorization
  aop:
    proxy-target-class: false

  session:
    jdbc:
      table-name: http_session
      cleanup-cron: 0 */5 * * * *
  security:
    user:
      name: razornd
      password: changeme
      roles: admin
    oauth2:
      authorizationserver:
        client:
          cli-app:
            require-proof-key: false
            registration:
              client-id: phototransit-cli
              client-name: PhotoTransit CLI
              client-secret: '${cli.client.secret}'
              client-authentication-methods: [ client_secret_basic, client_secret_post ]
              authorization-grant-types: [ urn:ietf:params:oauth:grant-type:device_code, refresh_token ]
              scopes:
                - 'origin-store:photo:upload'



gg.jte:
  use-precompiled-templates: true
  template-suffix: .kte


cli:
  client:
    secret: '{noop}changeme'
